---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  template: 
    metadata:
      labels: 
        app: front-app
    spec:
      containers:
      - name: front-app
        image: jesusbc/tfm-front-end:kubernetes
        ports:
        - containerPort: 4200
        envFrom:
          - configMapRef:
              name: app-vars-configmap