name: Compilar, empaquetar con Docker y subir al repositorio el servicio Front.

on:
  push:
    branches:
      - main
    paths:
      - 'tfm-front-end/**'

jobs:
  build-plots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v2

    - name: Logearse en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image servicio Front
      working-directory: ./tfm-front-end
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tfm-front-end:kubernetes .

    - name: Push Docker image servicio Front
      run: docker push ${{ secrets.DOCKER_USERNAME }}/tfm-front-end:kubernetes