name: Destruir la infraestructura de AWS

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.1

    - name: Configurar las credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: terraform init
      working-directory: ./infraestructura
      run: terraform init

    - name: terraform destroy
      working-directory: ./infraestructura
      run: |
        terraform destroy --target helm_release.nginx-externo-tf -auto-approve || true
        terraform destroy -auto-approve
